# fly.toml app configuration file generated for 02-docker-long-sea-2261 on 2025-09-15T21:52:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '02-docker-long-sea-2261'
primary_region = 'cdg'

[build]

[deploy]
  strategy = "rolling"
  wait_timeout = "3m"

[mounts]
  source = "data"
  destination = "/data"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"
  restart_limit = 3
  tls_skip_verify = false
  [http_service.checks.headers]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1